### ISSUE TITLE
Matestack Renderer: Project Plan

### ISSUE THREAD

**Issue by fiedl** [fiedl/matestack-renderer#1]
This project introduces a new renderer for [matestack-ui-core](https://github.com/matestack/matestack-ui-core).

The new renderer reduces dependencies and simplifies the interoperability of matestack components and view helpers.

## Project Plan

- [x] Add docker setup ➝ https://github.com/fiedl/matestack-renderer/commit/6f0f289ec13568245d1c0296647632bae28f82a7
- [x] Add github action for specs ➝ https://github.com/fiedl/matestack-renderer/commit/4e3f35489de6f863ab770785861a625b5ebf5733
- [x] Install [zeitwerk](https://github.com/fxn/zeitwerk) autoloader ➝ https://github.com/fiedl/matestack-renderer/commit/9d69fc658524a4543fa5b57f3efa4e5e90feb5f4
- [x] Add [rubocop](https://github.com/rubocop/rubocop) linter ➝ https://github.com/fiedl/matestack-renderer/commit/01d632945b8e7c195ec07dc8d2eaa9e6090ea4d8
- [x] Migrate base render buffer with specs from 2020 attempt ➝ https://github.com/fiedl/matestack-renderer/commit/a6f0170b33331d35d97a0f86f77d82797bf6a284
- [ ] Console
- [ ] Create dummy app
- [ ] Use dummy app for feature specs
- [ ] Migrate rails integration
- [ ] Migrate `render` helper
- [ ] Migrate implicit rendering
- [ ] Implement `Matestack::Component`
- [ ] Implement `Matestack::Page`
- [ ] Integrate `matestack-renderer` with `matestack-ui-core`

## References

Original proposal: https://github.com/matestack/matestack-ui-core/issues/377
